### ISSUE TITLE
博客点击下方页面导航链接报错

### ISSUE THREAD

**Issue by Wangjunyu** [sunnyhuang42/sunnyhuang.net#1]
点击下方的链接[http://ishanshan.im/page2/](第2页)和[http://ishanshan.im/page3/](第3页)会报错,`ishanshan.im 拒绝了我们的连接请求。`~

**Comment by sunnyhuang42** [comment]
咦，我这边无论在电脑还是手机浏览器或微信上，点击都是正常的没法复现 0.0

看了你 Issue 里给的两个链接，发现你给出的语法标记是 ` [http://ishanshan.im/page2/](第2页)` 。猜测是你访问我博客时启用了网页的自带翻译功能？如果是，试试不使用的话呢？

**Comment by Wangjunyu** [comment]
找到原因了, 用 https 访问没有问题, http 访问会报错.

**Comment by sunnyhuang42** [comment]
咦，你直接输入 http://ishanshan.im/page3/ 也会报错吗？
我这边如果直接输入 http://ishanshan.im/page3/ ，会自动跳转为 https 的地址正常显示，依然复现不了 0.0

**Comment by Wangjunyu** [comment]
对的~ 所以问题变成了两个:
1. 为什么 http 会报错
2. 如何让 http 的访问都转为 https...

另外,你用的 jekyll 有什么特殊的设置么?我的 blog.junyu.io 都是 http 的访问链接,也没有特殊设置过 https 的访问...

**Comment by sunnyhuang42** [comment]
>为什么 http 会报错
>如何让 http 的访问都转为 https...

你再试试？ 我加上了 http  的 301 转址，应该没问题了~

>你用的 jekyll 有什么特殊的设置么

用了  GitHub page 自带的 enforce HTTPS [Custom domains on GitHub Pages gain support for HTTPS | The GitHub Blog](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)

**Comment by Wangjunyu** [comment]
测试已经通过~点击链接会强制跳转到` https`了....
不过感觉访问速度和以前比有点变慢了,可以考虑 cdn 加快访问速度.

**Comment by sunnyhuang42** [comment]
恩呢之前的确比较慢，我删了 2 个 A 记录，现在快些了。你瞅瞅是不？
